### ISSUE TITLE
pokemon filter broken "undefined is not an object (x.pokemon.filter)"

### ISSUE THREAD

**Issue by Fabio1988** [WatWowMap/ReactMap#1083]
At some point the filter was broken by an update. I assume related to this change? https://github.com/WatWowMap/ReactMap/commit/9fb95f1cb34ebc3563ee6562bce28c2e33ff182c
It was only possible to restore functionality with removing browser data/cache

![image](https://github.com/user-attachments/assets/22248281-8ed0-44ba-bb2e-385d0a03e148)

**Comment by Mygod** [comment]
Full stack trace please?

**Comment by Fabio1988** [comment]
```
reactmap  |   nginx_id: undefined,
reactmap  |   trace: "TypeError: Cannot read properties of undefined (reading 'filter')\n" +
reactmap  |     '    at /1-36-0-develop-8-D5NMdsCG.js:1:169017\n' +
reactmap  |     'r (../node_modules/zustand/esm/vanilla.mjs:5:54)\n' +
reactmap  |     'i.setState (../node_modules/zustand/esm/middleware.mjs:481:4)\n' +
reactmap  |     '    at /1-36-0-develop-8-D5NMdsCG.js:1:168541\n' +
reactmap  |     'V1 (../node_modules/react-dom/cjs/react-dom.production.min.js:243:331)\n' +
reactmap  |     'Bd (../node_modules/react-dom/cjs/react-dom.production.min.js:285:110)\n' +
reactmap  |     'vH (../node_modules/react-dom/cjs/react-dom.production.min.js:282:408)\n' +
reactmap  |     'Ac (../node_modules/react-dom/cjs/react-dom.production.min.js:280:397)\n' +
reactmap  |     'nk (../node_modules/react-dom/cjs/react-dom.production.min.js:272:438)\n' +
reactmap  |     'qu (../node_modules/react-dom/cjs/react-dom.production.min.js:127:104)'
```

**Comment by Mygod** [comment]
Fixed via https://github.com/WatWowMap/ReactMap/commit/8a4db0f71236f17fbd0509722fd474ff9f649365.
