### ISSUE TITLE
Docker Setup Issue

### ISSUE THREAD

**Issue by MaxTuecke** [WatWowMap/ReactMap#161]
I was trying to run thought the docker setup. I have a running container that the server is running on. However when I try to connect to the localhost site, I get:
"Unable to connect to the server at this time. Trying again immediately will only cause more issues. Please try again in a few minutes."
When I docker logs the container im getting this error:

Error: connect ECONNREFUSED 127.0.0.1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)
    --------------------
    at Protocol._enqueue (/home/node/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/home/node/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/home/node/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/home/node/node_modules/mysql/lib/Pool.js:48:16)
    at Pool.query (/home/node/node_modules/mysql/lib/Pool.js:202:8)
    at MySQLStore.query (/home/node/node_modules/express-mysql-session/index.js:432:33)
    at MySQLStore.get (/home/node/node_modules/express-mysql-session/index.js:162:8)
    at session (/home/node/node_modules/express-session/index.js:481:11)
    at Layer.handle [as handle_request] (/home/node/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/node/node_modules/express/lib/router/index.js:317:13)

I am just using the example for the config files.

Ive been playing with this for a little bit and im not really sure what is breaking or why. Any help would be greatly appreciated.

**Comment by Fabio1988** [comment]
You have not setup the database for reactmap? I don't think you have entered all db config options in `config.json`?

**Comment by TurtIeSocks** [comment]
Any luck @MaxTuecke with Fabio's suggestion?

**Comment by MaxTuecke** [comment]
Yeah I cant get the data bases to create properly. Im not sure why.

**Comment by Fabio1988** [comment]
So you don't run RDM correctly or do you have problems to connect to rdm database?
ReactMap needs connection to 2 databases... manualDB and RDM db

**Comment by TurtIeSocks** [comment]
Going to go ahead and close this for now. If OP is still seeing issues, then I'm happy to open it up again and go through it.
